const SET_SUGGESTIONS = 'SET_SUGGESTIONS'
const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'
const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER'
const SET_FORECAST = 'SET_FORECAST'
const SET_FAVORITE_LOCATION_KEYS = 'SET_FAVORITE_LOCATION_KEYS'
const SET_FAVORITE_LOCATIONS_CURRENT_WEATHER = 'SET_FAVORITE_LOCATIONS_CURRENT_WEATHER'

export {
    SET_SUGGESTIONS,
    SET_CURRENT_LOCATION,
    SET_CURRENT_WEATHER,
    SET_FORECAST,
    SET_FAVORITE_LOCATION_KEYS,
    SET_FAVORITE_LOCATIONS_CURRENT_WEATHER,
}