const APP_NAME = 'Weather'

const {
    REACT_APP_WEATHER_API_KEY: WEATHER_API_KEY,
    REACT_APP_LOCATION_AUTOCOMPLETE_PATH: LOCATION_AUTOCOMPLETE_PATH,
    REACT_APP_CURRENT_WEATHER_PATH: CURRENT_WEATHER_PATH,
    REACT_APP_FORECAST_PATH: FORECAST_PATH,
} = process.env

const ROUTES = {
    WEATHER: '/',
    FAVORITES: '/favorites',
}

const FAVORITE_LOCATION_KEYS = 'FAVORITE_LOCATION_KEYS'

export {
    APP_NAME,
    WEATHER_API_KEY,
    LOCATION_AUTOCOMPLETE_PATH,
    CURRENT_WEATHER_PATH,
    FORECAST_PATH,
    ROUTES,
    FAVORITE_LOCATION_KEYS,
}